### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by turbolocust** [IonxSolutions/docker-images#5]
I see that the latest supported PostgreSQL release is 12.2. There is 12.8, 13.4 and 14.0 available now. According to Docker Hub, the last image was pushed 2 years ago (see on [DockerHub](https://hub.docker.com/r/ionx/postgres-plv8/tags)).

Will this repository be updated any time soon?

**Comment by colin-anderson** [comment]
Yes, it's still being maintained. I expect an update to 12.8 will be added soon, with 13.x a few months after, and 14.x several months after that.

**Comment by colin-anderson** [comment]
Forgot to mention, 12.8 was added on 09-Nov-2021 (13.x and 14.x are still to come)
